### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by ImmortalDragonm** [erikerlandson/st_tree#14]
VC 2013
Then i compile any examles i get this warning:
warning C4099: 'st_tree::tree<node_base<Tree,Node,ChildContainer>::tree_type::data_type,Tree::cs_model_type,Tree::allocator_type>' : type name first seen using 'struct' now seen using 'class'

many times

**Comment by ImmortalDragonm** [comment]
i think you must change 
friend class
to
friend struct

**Comment by erikerlandson** [comment]
@ImmortalDragonm I don't have VC, can you test this PR just to confirm it resolves your warnings?

**Comment by ImmortalDragonm** [comment]
yes. no warnings at all? after i changed.
I can send you patch or you can change 13 class to stuct in st_tree_nodes.h

**Comment by erikerlandson** [comment]
@ImmortalDragonm I merged in the fix, thanks for the feedback!
