### ISSUE TITLE
C++11 compatibility

### ISSUE THREAD

**Issue by cafhach** [erikerlandson/st_tree#16]
Hi there, I would like to use this very cool tree implementation, but if I add -std=c++11 to gcc 4.8.4 I cannot - for instance - compile the x03_keyed_children.cpp example anymore because I get prompted some weird conversion problem for a call deep within the st_tree code... something like "no known conversion from [...] const iterator [...] to [...] const_iterator".

/usr/include/c++/4.8/bits/stl_map.h:746:7: note: std::map<_Key, _Tp, _Compare, _Alloc>::iterator std::map<_Key, _Tp, _Compare, _Alloc>::erase(std::map<_Key, _Tp, _Compare, _Alloc>::const_iterator, std::map<_Key, _Tp, _Compare, _Alloc>::const_iterator) [with _Key = const std::basic_string<char>*; _Tp = st_tree::detail::node_keyed<st_tree::tree<int, st_tree::keyed<std::basic_string<char> > >, int, std::basic_string<char>, std::less<std::basic_string<char> > >*; _Compare = st_tree::detail::ptr_less<std::less<std::basic_string<char> > >; _Alloc = std::allocator<int>; std::map<_Key, _Tp, _Compare, _Alloc>::iterator = std::_Rb_tree_iterator<std::pair<const std::basic_string<char>* const, st_tree::detail::node_keyed<st_tree::tree<int, st_tree::keyed<std::basic_string<char> > >, int, std::basic_string<char>, std::less<std::basic_string<char> > >*> >; std::map<_Key, _Tp, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<std::pair<const std::basic_string<char>* const, st_tree::detail::node_keyed<st_tree::tree<int, st_tree::keyed<std::basic_string<char> > >, int, std::basic_string<char>, std::less<std::basic_string<char> > >*> >]
       erase(const_iterator __first, const_iterator __last)
       ^
/usr/include/c++/4.8/bits/stl_map.h:746:7: note:   no known conversion for argument 1 from ‘const iterator {aka const st_tree::detail::valmap_iterator_adaptor_forward<std::_Rb_tree_iterator<std::pair<const std::basic_string<char>* const, st_tree::detail::node_keyed<st_tree::tree<int, st_tree::keyed<std::basic_string<char> > >, int, std::basic_string<char>, std::less<std::basic_string<char> > >*> >, st_tree::detail::dref_second_vmap<std::pair<const std::basic_string<char>* const, st_tree::detail::node_keyed<st_tree::tree<int, st_tree::keyed<std::basic_string<char> > >, int, std::basic_string<char>, std::less<std::basic_string<char> > >*> > >}’ to ‘std::map<const std::basic_string<char>*, st_tree::detail::node_keyed<st_tree::tree<int, st_tree::keyed<std::basic_string<char> > >, int, std::basic_string<char>, std::less<std::basic_string<char> > >*, st_tree::detail::ptr_less<std::less<std::basic_string<char> > >, std::allocator<int> >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const std::basic_string<char>* const, st_tree::detail::node_keyed<st_tree::tree<int, st_tree::keyed<std::basic_string<char> > >, int, std::basic_string<char>, std::less<std::basic_string<char> > >*> >}’

**Comment by erikerlandson** [comment]
@cafhach thanks for letting me know, I'll try to figure this out soon

**Comment by erikerlandson** [comment]
@cafhach The fix on PR #17 is working for me, if it works for you too I'll merge it
