### ISSUE TITLE
No stateful allocator?

### ISSUE THREAD

**Issue by Raildex** [erikerlandson/st_tree#26]
STL containers allow passing the allocator (not the type) as a constructor argument. I'd like to see it here aswell.

**Comment by erikerlandson** [comment]
Hi @Raildex, is it sufficient to support a constructor that takes an allocator:
```cpp
tree(const node_allocator_type& a) : _root(NULL), _node_allocator(a) {}
```

**Comment by erikerlandson** [comment]
re-opening, I'll close when I push an upate with new allocator

**Comment by erikerlandson** [comment]
@Raildex  I pushed a fix to head of `develop` branch that defines new constructor:
```
tree(const node_allocator_type& a) : _root(NULL), _node_allocator(a) {}
```

If that works for you, let me know and I'll close this issue

**Comment by Raildex** [comment]
it works perfectly fine now 👍

**Comment by erikerlandson** [comment]
thank you!
